### ISSUE TITLE
Compile error in vvs.h on Linux build

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#12]
/home/dg/work/deepguider/examples/unit_test/vvs.h:87:33: error: cast from ‘dg::DirectedGraph<dg::Point2ID, double>::Edge* {aka dg::EdgeType<dg::Point2ID, double>*}’ to ‘int’ loses precision [-fpermissive]
         int _isTrue_ = (int)(EXP);

**Comment by roricljy** [comment]
We need to use 'intptr_t' type instead of 'int' in linux 64bit system.

**Comment by sunglok** [comment]
I added '!= NULL' and updated OpenCX. (cf56260cd18bb56b1eec47cd943198474c3da5f2)

**Comment by roricljy** [comment]
I works good now!
