### ISSUE TITLE
segmentation fault in embedded python

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#23]
When run 'import cv2' in the embedded python module, segmentation fault occurs.
It seems that it occurs when the wrapper c++ module use the GUI module of the OpenCV.

**Comment by roricljy** [comment]
It is found that the error occurs due to the collision of Qt between python opencv and system opencv.
It is resolved by installing opencv-contrib-python-headless in the embedded python instead of opencv-contrib-python.

**Comment by aseuteurideu** [comment]
it works for me on intersection_cls example with this version of opencv-contrib-python-headless==4.1.2.30. Didn't work on the newest version (4.2.0.34)
