### ISSUE TITLE
runtime error at MapManager::load()

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#24]
When call MapManager::load(), the following assertion error occurs:
dg_test: /home/dg/work/deepguider/examples/dg_test/../../EXTERNAL/rapidjson/include/rapidjson/document.h:1139: rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `false' failed.
/bin/bash: line 1:  7567 Aborted                 (core dumped) ./dg_test

**Comment by zeozeo7142** [comment]
The error occurred because "width" item is deleted from edge information.
Currently, the error has been solved.
