### ISSUE TITLE
Compile Error on Linux (MapManager)

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#25]
The following compile error occurred:
src/map_manager/map_manager.hpp:70:14: error: extra qualification ‘dg::MapManager:’ on member ‘to_utf8’ [-fpermissive]
  std::string MapManager::to_utf8(uint32_t cp);
src/map_manager/map_manager.hpp:90:7: error: extra qualification ‘dg::MapManager::’ on member ‘getPath’ [-fpermissive]
  Path MapManager::getPath();

**Comment by zeozeo7142** [comment]
I fixed the error.
