### ISSUE TITLE
lat/lon order (MapManager)

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#27]
lat/lon order is inconsistent in the following functions:
- bool downloadMap(double lat, double lon, double radius);
- cv::Point2i lonlat2xy(double lon, double lat, int z);
- bool load(double lat, double lon, double radius);// (double lon = 128, double lat = 38, int z = 19);
- bool downloadPath(double start_lat, double start_lon, double goal_lat, double goal_lon, int num_paths = 2);
- bool generatePath(double start_lat, double start_lon, double goal_lat, double goal_lon, int num_paths = 2);

1. it should be lat, lon order according the design specification of the deepguider system
1. additionally, it's better to use consistent argument order to prevent possible programming error

**Comment by zeozeo7142** [comment]
I fixed lat/lon order according the design specification of the DeepGuider system.
