### ISSUE TITLE
typo in MapManager::getMap(Path path)

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#29]
in the implementation of the function, load (lon, lat, z) should be load(lat, lon, z).
------
Map& MapManager::getMap(Path path)
{
	//TODO
	CURL *curl;

	double lon = 128;
	double lat = 37.5;
	int z = 19;

	load(lon, lat, z);

	return getMap();
}

**Comment by zeozeo7142** [comment]
I fixed the error. And I plan to modify the function as a whole.
