### ISSUE TITLE
Wrong lat/lon value in the returned dg::Map

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#30]
The lat/lon value of the returned dg::Map::Node in the following example is incorrect. (lat and lon seem to be swapped)

// example test code
dg::Path path = m_map_manager.getPath();
dg::Map map = m_map_manager.getMap(path);
dg::Map::Node* node = map.findNode(path.m_points.front());
prnitf("lat=%lf, lon=%lf\n", node->data.lat, node->data.lon);

// output
lat=127.367581, lon=36.382170

**Comment by zeozeo7142** [comment]
![image](https://user-images.githubusercontent.com/51986901/75835602-a5a1a080-5e02-11ea-8a84-267844eca3b5.png)
It seems to be errors in the Topological Map server. I will post this issue on github.
