### ISSUE TITLE
Possible Inconsistency Related to NodeType & EdgeType

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#33]
Member access to dg::Map::Edge & dg::Map::Node in current implementation of dg::Map and dg::DirectedGraph:

// Node
dg::Map::Node* node = dg::Map::findNode(id);
dg::ID id = node->data.id;
int type = node->data.type;
double lat = node->data.lat;

// Edge
dg::Map::Edge* edge = dg::Map::findEdge(node_id_from, node_id_to);
double length = edge->cost.length;
int type = edge->cost.type;

1. dg::NodeInfo used as node->data but dg::EdgeInfo to edge->cost. The naming is inconsistent and little bit confusing.
2. node->data.type, edge->cost.type can be misinterpreted as the type of data and type of cost (not as the type of node and edge), respectively.

**Comment by sunglok** [comment]
The name `cost` came from graph search algorithms. In the graph search, edge traversal cost is the only edge information.
Anyway, I has removed `dg::Map`'s dependency on `dg::DirectedGraph`. This naming issue is cleared. ^^
