### ISSUE TITLE
Adding macro in <vvs.h>

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#35]
Macros defined in <vvs.h> are really great and useful!
As suggestion, it will be useful if there is macro that only checks the expression without calling the assert().
Currently, VVS_CHECK_TRUE() and VVS_CHECK_FALSE() calls assert() when the check fails.
Sometimes we may want to check the result and continue the program.

**Comment by sunglok** [comment]
It's good idea. I add a macro to deactivate `assert` if `VVS_NO_ASSERT` is declared before `#include "vvs.h"`. Please refer 638154c04cd5c1a6cf8d351541f0fe8bab670dc9.
