### ISSUE TITLE
Invalid Stree View ID (VPS)

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#36]
The returned street view image ID's from VPS module have following 2 problems:
 p1. the returned top-3 ID's are always same (id = 18446744073709551615, 20 digits)
 p2. the returned ID's are invalid (valid ID's should be 16 digits)

We need to check both python code and c++ wrapper.

**Comment by ccsmm78** [comment]
This is a bug caused by Python's output being passed as a list of strings instead of integers.  To solve this, I did explicit type casting with int () and float () for ID and confodence respectively.
