### ISSUE TITLE
Localizer::applyLocClue() fails

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#37]
Localizer::applyLocClue(dg::ID id, ...) always fails when the input argument 'id' is from Street View ID

**Comment by sunglok** [comment]
`dg::Map` does not contain information (ID and ...) for POI and streetview. It will resolved after including the information to `dg::Map`.

**Comment by roricljy** [comment]
ID checking for StreetView and POI has been already implemented in MapManager. So you can apply it now. Please check it and close this issue. I added other assignees for the reference.
