### ISSUE TITLE
StreeView and POI access in MapManager

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#39]
- We need some unified api's for accessing POI and streetview maps.
- Current interface of MapManager::getPOI have to be modified to return dg::ID or POI node.

**Comment by sunglok** [comment]
I think that information for POI and streetview can be merged with `dg::Map`, so I made dummy routines for them.

**Comment by zeozeo7142** [comment]
Interface of MapManager::getPOI(getStreetView) was modified to return std::list<POI>(<StreetView>).
