### ISSUE TITLE
Abnormal edges in returned dg::Map

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#43]
The returned map by dg::MapManager::load(...) seems to contain strange edges which are not likely to be in the real map.

**Comment by roricljy** [comment]
It is found that this error occurred because the map servers returned wrong latitude and longitude value for some nodes. I will close it after the map server is fixed.

**Comment by zeozeo7142** [comment]
Temporarily, it will be modified to automatically change the latitude and longitude that have been swapped.
