### ISSUE TITLE
Compliance with naming conventions [Guidance]

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#44]
guidance.cpp & hpp seems not to follow the naming conventions defined in design specification of deepguider system.

Please refer to Appendix D of the document: https://docs.google.com/document/d/1dRjMiSUTl3Xk458OMz18fDS-3dWqUp7EGz2ZzQncIoc/edit?usp=sharing

**Comment by seohyunatwork** [comment]
m_initGuides ==> m_guides
m_pathNodeIds ==> m_path_nodes
m_pathEdgeIds ==> m_path_edges
m_curGuideIdx  ==> m_guide_idx
m_edgeElapse ==> m_edge_progress
etc..
I tried to change incompliant names when they are found by me, in the today's commit. 
I will close this issue. But whenever you find any incomplicancy again, just let me know.
