### ISSUE TITLE
Pointer to temporal instance (MapManager::generatePath)

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#47]
In function MapManager::generatePath(...), PathElement::node and PathElement::edge are initialized with the address of temporal local variables which are not valid after termination of the function.

They should be initialized to point out the Nodes and Edges in the downloaded Map.

**Comment by seohyunatwork** [comment]
First, we decided to include only Node IDs in the path.
Second, we decided to include both Node's and Edge's IDs.
Now that, there is PathElement with Node* and Edge*, 
I think its OK to change the path with PathElement.

**Comment by sunglok** [comment]
Now, `dg::Path` contains points to nodes and edges. It is dangerous and ambiguous whether `dg::Path` indicates valid instances or not. How about using IDs instead of pointers.

**Comment by zeozeo7142** [comment]
I solved this issue #47.
