### ISSUE TITLE
Path specification mismatch (MapManager::generatePath)

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#48]
If a returned path from the map server is id1, id2, ....idn, the dg::Path should be [{id1, id2}, {id3, id4}, ...} when {id1, id2} denotes a dg::PathElement with node id1 and edge id2. However, current implementation of MapManager::generatePath() outputs [{id1, null}, {null, id2}, ...].

**Comment by seohyunatwork** [comment]
For Guidance point of view, changing  [{Node1, null}, {null, Edge2}, ...] to  [{Node1, Edge2}, {Node3, Edge4, ... }] is OK.

**Comment by zeozeo7142** [comment]
I solved this issue #48.
