### ISSUE TITLE
[cx::Algorithm] setParamValue() can cause error depending on OpenCV version

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#50]
In Linux and OpenCV 3.3, cx::Algorithm::setParamValue(const std::string& __param__, double value) cause error when the type of member variable associated with the __param__ name is __int__.

example case:
```
int GraphPainter::m_edge_thickness;
GraphPainter::setParamValue("edge_thickness", 2);
// internally, it generates yml string -> "edge_thickness: 2.00000"
// and then parsed into int type variable (not double type).
// after the execution of setParamValue, m_edge_thickness became very very large value unexpectedly. 
```
I'm not sure what will happen with other opencv versions or on windows.

**Comment by sunglok** [comment]
I expect that `double` to `int` might be no problem. I will check and update its progress.

**Comment by roricljy** [comment]
I don't know why but it occurs when the code is executed in ROS.

**Comment by roricljy** [comment]
resolved (it works in ros melodic)
