### ISSUE TITLE
[MapManager] server ip setting

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#56]
1. Bug fix: in the function MapManager::generatePath(), **getMap(path)** should be **getMap(path, ip)**
```
	ok = parsePath(json);
	if (!ok) return false;

	Path path = m_path;
	getMap(path); ----> getMap(path, ip);
```

2. Revision suggestion
I think it's also good to use local variable _ip_ and share it across the functions in MapManager instead of providing it as argument of each function... In that case, the default server ip can be changed explicitly by some api call when it is necessary.

**Comment by roricljy** [comment]
It took 2 hours to find this.. t.t At the beginning, I thought that my curl library or network has problem..

**Comment by zeozeo7142** [comment]
I'm really sorry! I thought I was looking at my codes as a whole, but I couldn't find it(getMap(path)).

**Comment by zeozeo7142** [comment]
I made setter and getter functions for server IP address.
