### ISSUE TITLE
[Mobaxterm] ASSERT: "false" in file qasciikey.cpp, line 495, core dump at imshow() in main.cpp

### ISSUE THREAD

**Issue by ccsmm78** [deepguider/DeepGuider#61]
This issue is only necessary for those who connect to linux using mobaxterm and run the program.
In particular, it occurs when the image window is created by calling opencv's imshow () function. At this time, when you do other work with the mouse or keyboard, the program will be forcibly killed and the following message will be displayed. :
**_ASSERT: "false" in file qasciikey.cpp, line 495, core dump_**

The solution is quite simple :
Mobaxterm --> Settings --> Configuration --> X11[Tab] --> un-checking  "Unix-compatible keyboard" --> OK

refer : 
https://stackoverflow.com/questions/53310086/opencv-gving-error-assert-false-in-file-qasciikey-cpp-line-495-on-multiple

This issue will be closed by me after a week.

**Comment by roricljy** [comment]
Thanks great tip!
I haven't had the problem but I changed the setting as you suggested. And it works with no problem.
