### ISSUE TITLE
[VPS] reuse of history

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#64]
VPS module seems like to use invalid old streetview images when the StreetView server returns empty result (it means that there is no nearby streetview images in the range).  I guess they are cached ones in previous run of VPS.

**Comment by ccsmm78** [comment]
Thanks for bug report.
Yes, I got it.
I fixed that you mentioned

For checking this, one can run vps_test while setting lat to 40 which means out of range : 93 double gps_lat = 40; in examples/vps_test/main.cpp
thread_vps.apply() will return zero ID and confidence.
