### ISSUE TITLE
[VPS] return outputs

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#67]
It looks like that VPS still returns N StreetViews with zero id when there is no nearby streetviews.
![image](https://user-images.githubusercontent.com/48148835/77865636-58321b00-726a-11ea-8263-65abd6f94b8c.png)

**Comment by ccsmm78** [comment]
Yes, that's what I intended. When there is no 'streetview images' to be compared, the result (ID, confidence) will be output as zero. Please recommend if there is another way.

If there is no pointer problem when returning the result from apply (), I can return only the valid result to the list. Even in the case above, null (or '[]') will be returned.

**Comment by roricljy** [comment]
That's no problem if it is intended.
