### ISSUE TITLE
[dg_test] Is it okay to show the lat/lon on the map?

### ISSUE THREAD

**Issue by ccsmm78** [deepguider/DeepGuider#68]
Since this program is open to the public via github, it seems necessary to pay attention to the latitude and longitude indication.

It may be illegal to show latitude and longitude on the map.
I think it would be better to display them in a specific coordinate system that we can understand, not latitude longitude.

국토지리정보원(공간영상과)에 문의한 내용(2019년도):
1.	위경도 위치 정보의 경우, 인터넷,모바일 장치 등에 위경도 숫자 표시 금지 조항이 있음.
2.	위경도 위치 정보를 프로그램 내에서 활용하는 것은 허용됨(출력없이) : 이것이 불허되면, 네비게이션 등의 응용 개발이 불가하기 때문. 단, 현 위치의 위,경도가 표시되면 안됨.

**Comment by roricljy** [comment]
Thank you for checking it.
I modified the code not to display gps coordinate on the GUI map.
