### ISSUE TITLE
dg_core.hpp

### ISSUE THREAD

**Issue by minnjung** [deepguider/DeepGuider#7]
poi_recog의 c++ 연동 확인을 해보려고 하는데,
core 내부의 header 파일들이 서로 include하는 것들의 위치가 바뀌어서 그런지 오류가 뜹니다.
제가 임의로 건드리면 안될 것 같아서 확인 부탁드립니다.

**Comment by roricljy** [comment]
Can you leave what kind of test (or setting?) you do, and what the error message was?

**Comment by roricljy** [comment]
The problem can be solved by adding deepguider/src folder to the compiler's include path.
