### ISSUE TITLE
[Map] findNode, findEdge not working

### ISSUE THREAD

**Issue by seohyunatwork** [deepguider/DeepGuider#73]
I tried following test code, but it's not working. `Node` and `edge` are not appointed.

```
map_manager.getMap(559542564800095, 700, map);
map_manager.getPath(36.381873, 127.36803, 36.384063, 127.374733, path);
Node* node = map.findNode(path.pts[0].node->id);
Edge* edge = map.findEdge(path.pts[0].edge->id);
```

It looks like the map contains nodes and edges info, but not lookup_nodes and lookup_edges info.

**Comment by zeozeo7142** [comment]
Have you tested the new version, Topological Map Server v0.3?
I pushed the test code to GitHub for the new version.
(Please change the node ID and test it.)

**Comment by zeozeo7142** [comment]
This is a problem that occurs because the node existing in the Routing Server does not exist in the Topological Map Server.
I will post this issue on TopoMapAPI repository.

**Comment by roricljy** [comment]
resoloved
